FROM debian:stable-slim

RUN apt-get update && \
    apt-get install --no-install-recommends -y \
        aws-cli jq && \
	apt-get clean -y && \
rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]