FROM node:10-stretch

RUN apt-get update && \
    apt-get install --no-install-recommends -y \
        python3 jq python3-pip python3-setuptools groff less && \
	apt-get clean -y && \
rm -rf /var/lib/apt/lists/*

RUN pip3 no-cache-dir install -upgrade awscli

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
