FROM node:10-slim

LABEL version="1.0.0"
LABEL repository="https://github/lannonbr/deploy-lambda-action"
LABEL maintainer="Benjamin Lannon <benjamin@lannonbr.com>"

LABEL com.github.actions.name="Deploy Lambda PR Comment Action"
LABEL com.github.actions.description="Will create a comment in merged PRs to initiate the process for deploying a lambda function to AWS"
LABEL com.github.actions.icon="message-circle"
LABEL com.github.actions.color="purple"

ADD package.json /package.json
ADD package-lock.json /package-lock.json
WORKDIR /
COPY . /

RUN npm ci

ENTRYPOINT ["node", "/index.js"]